import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import React, { useState } from "react";
import Navbar from "@/components/navbar";
import owner from "../public/images/owner.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        {/* <section className="container">
          <div className="row">
            <div className="col-lg-6 mt-5 pt-5">
              <h2>Muoghalu Ijeoma Florence</h2>
            </div>
            <Image
              style={{ height: "500px", width: "auto" }}
              className="col-lg-6 rounded float-end mb-5 pb-5"
              src={owner}
              alt={"/"}
            />
          </div>
        </section> */}
      </main>
    </>
  );
}

// export function Navbar() {
//   let [width, setWidth] = useState(window.innerWidth);
//   useEffect(() => {
//     window.addEventListener("resize", () => setWidth(window.innerWidth));
//   });
//   return (
//     <div className="nav-container">
//       {width <= 699 ? <Navbar /> : <Navbar />}
//     </div>
//   );
// }
// function useEffect(arg0: () => void) {
//   throw new Error("Function not implemented.");
// }
